// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msgdef.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Msgpacket {

  /// <summary>Holder for reflection information generated from msgdef.proto</summary>
  public static partial class MsgdefReflection {

    #region Descriptor
    /// <summary>File descriptor for msgdef.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgdefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxtc2dkZWYucHJvdG8SCW1zZ3BhY2tldCrBBAoRUEJfTVNHX0lOVEVSX1RZ",
            "UEUSFgoSX1BCX01TR19JTlRFUl9OVUxMEAASIQodX1BCX01TR19JTlRFUl9R",
            "VUVTUlZfUkVHSVNURVIQARIlCiFfUEJfTVNHX0lOVEVSX1FVRVNSVl9SRUdJ",
            "U1RFUl9SRVMQAhIkCiBfUEJfTVNHX0lOVEVSX1FVRVNSVl9PRkZMSU5FX05U",
            "RhADEiMKH19QQl9NU0dfSU5URVJfUVVFU1JWX09OTElORV9OVEYQBBIgChxf",
            "UEJfTVNHX0lOVEVSX1FVRVNSVl9DT05ORUNUEAUSJAogX1BCX01TR19JTlRF",
            "Ul9RVUVTUlZfQ09OTkVDVF9SRVMQBhIlCiFfUEJfTVNHX0lOVEVSX1FVRUNF",
            "TlRFUl9IRUFSVEJFQVQQBxIpCiVfUEJfTVNHX0lOVEVSX1FVRUNFTlRFUl9I",
            "RUFSVEJFQVRfUkVTEAgSIgoeX1BCX01TR19JTlRFUl9RVUVTUlZfSEVBUlRC",
            "RUFUEAkSJgoiX1BCX01TR19JTlRFUl9RVUVTUlZfSEVBUlRCRUFUX1JFUxAK",
            "EhkKFV9QQl9NU0dfSU5URVJfU1JWX1JFRxALEh0KGV9QQl9NU0dfSU5URVJf",
            "U1JWX1JFR19SRVMQDBIfChtfUEJfTVNHX0lOVEVSX1NSVl9IRUFSVEJFQVQQ",
            "DRIjCh9fUEJfTVNHX0lOVEVSX1NSVl9IRUFSVEJFQVRfUkVTEA4SGQoVX1BC",
            "X01TR19JTlRFUl9TUlZfTVNHEA8qigEKEFBCX1JFU1BPTlNFX0NPREUSGQoV",
            "UEJfUkVTUE9OU0VfQ09ERV9GYWlsEAASFwoTUEJfUkVTUE9OU0VfQ09ERV9P",
            "SxABEiMKH1BCX1JFU1BPTlNFX0NPREVfUnBjX25vdF9hY2NlcHQQAhIdChlQ",
            "Ql9SRVNQT05TRV9DT0RFX3JlZGlyZWN0EANCDloMLi87bXNncGFja2V0YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Msgpacket.PB_MSG_INTER_TYPE), typeof(global::Msgpacket.PB_RESPONSE_CODE), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PB_MSG_INTER_TYPE {
    [pbr::OriginalName("_PB_MSG_INTER_NULL")] PbMsgInterNull = 0,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_REGISTER")] PbMsgInterQuesrvRegister = 1,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_REGISTER_RES")] PbMsgInterQuesrvRegisterRes = 2,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_OFFLINE_NTF")] PbMsgInterQuesrvOfflineNtf = 3,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_ONLINE_NTF")] PbMsgInterQuesrvOnlineNtf = 4,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_CONNECT")] PbMsgInterQuesrvConnect = 5,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_CONNECT_RES")] PbMsgInterQuesrvConnectRes = 6,
    [pbr::OriginalName("_PB_MSG_INTER_QUECENTER_HEARTBEAT")] PbMsgInterQuecenterHeartbeat = 7,
    [pbr::OriginalName("_PB_MSG_INTER_QUECENTER_HEARTBEAT_RES")] PbMsgInterQuecenterHeartbeatRes = 8,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_HEARTBEAT")] PbMsgInterQuesrvHeartbeat = 9,
    [pbr::OriginalName("_PB_MSG_INTER_QUESRV_HEARTBEAT_RES")] PbMsgInterQuesrvHeartbeatRes = 10,
    [pbr::OriginalName("_PB_MSG_INTER_SRV_REG")] PbMsgInterSrvReg = 11,
    [pbr::OriginalName("_PB_MSG_INTER_SRV_REG_RES")] PbMsgInterSrvRegRes = 12,
    [pbr::OriginalName("_PB_MSG_INTER_SRV_HEARTBEAT")] PbMsgInterSrvHeartbeat = 13,
    [pbr::OriginalName("_PB_MSG_INTER_SRV_HEARTBEAT_RES")] PbMsgInterSrvHeartbeatRes = 14,
    [pbr::OriginalName("_PB_MSG_INTER_SRV_MSG")] PbMsgInterSrvMsg = 15,
  }

  public enum PB_RESPONSE_CODE {
    [pbr::OriginalName("PB_RESPONSE_CODE_Fail")] Fail = 0,
    [pbr::OriginalName("PB_RESPONSE_CODE_OK")] Ok = 1,
    [pbr::OriginalName("PB_RESPONSE_CODE_Rpc_not_accept")] RpcNotAccept = 2,
    [pbr::OriginalName("PB_RESPONSE_CODE_redirect")] Redirect = 3,
  }

  #endregion

}

#endregion Designer generated code
