// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.1
// source: msg.proto

package msgpacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSG_TYPE int32

const (
	MSG_TYPE__MSG_NULL       MSG_TYPE = 0
	MSG_TYPE__MSG_RPC        MSG_TYPE = 1
	MSG_TYPE__MSG_RPC_RES    MSG_TYPE = 2
	MSG_TYPE__MSG_SRV_REPORT MSG_TYPE = 3
	MSG_TYPE__MSG_MAX        MSG_TYPE = 100
	MSG_TYPE__MSG_TEST       MSG_TYPE = 101
	MSG_TYPE__MSG_TEST_RES   MSG_TYPE = 102
	MSG_TYPE__MSG_LOGIN      MSG_TYPE = 103
	MSG_TYPE__MSG_LOGIN_RES  MSG_TYPE = 104
)

// Enum value maps for MSG_TYPE.
var (
	MSG_TYPE_name = map[int32]string{
		0:   "_MSG_NULL",
		1:   "_MSG_RPC",
		2:   "_MSG_RPC_RES",
		3:   "_MSG_SRV_REPORT",
		100: "_MSG_MAX",
		101: "_MSG_TEST",
		102: "_MSG_TEST_RES",
		103: "_MSG_LOGIN",
		104: "_MSG_LOGIN_RES",
	}
	MSG_TYPE_value = map[string]int32{
		"_MSG_NULL":       0,
		"_MSG_RPC":        1,
		"_MSG_RPC_RES":    2,
		"_MSG_SRV_REPORT": 3,
		"_MSG_MAX":        100,
		"_MSG_TEST":       101,
		"_MSG_TEST_RES":   102,
		"_MSG_LOGIN":      103,
		"_MSG_LOGIN_RES":  104,
	}
)

func (x MSG_TYPE) Enum() *MSG_TYPE {
	p := new(MSG_TYPE)
	*p = x
	return p
}

func (x MSG_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (MSG_TYPE) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x MSG_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_TYPE.Descriptor instead.
func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

type MSG_RPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId   int64  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgType int32  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgBin  []byte `protobuf:"bytes,3,opt,name=msg_bin,json=msgBin,proto3" json:"msg_bin,omitempty"`
}

func (x *MSG_RPC) Reset() {
	*x = MSG_RPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_RPC) ProtoMessage() {}

func (x *MSG_RPC) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_RPC.ProtoReflect.Descriptor instead.
func (*MSG_RPC) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MSG_RPC) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MSG_RPC) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MSG_RPC) GetMsgBin() []byte {
	if x != nil {
		return x.MsgBin
	}
	return nil
}

type MSG_RPC_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId   int64  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgType int32  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgBin  []byte `protobuf:"bytes,3,opt,name=msg_bin,json=msgBin,proto3" json:"msg_bin,omitempty"`
}

func (x *MSG_RPC_RES) Reset() {
	*x = MSG_RPC_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_RPC_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_RPC_RES) ProtoMessage() {}

func (x *MSG_RPC_RES) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_RPC_RES.ProtoReflect.Descriptor instead.
func (*MSG_RPC_RES) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MSG_RPC_RES) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MSG_RPC_RES) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MSG_RPC_RES) GetMsgBin() []byte {
	if x != nil {
		return x.MsgBin
	}
	return nil
}

type MSG_SRV_REPORT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrvId int64 `protobuf:"varint,1,opt,name=srv_id,json=srvId,proto3" json:"srv_id,omitempty"`
}

func (x *MSG_SRV_REPORT) Reset() {
	*x = MSG_SRV_REPORT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_SRV_REPORT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_SRV_REPORT) ProtoMessage() {}

func (x *MSG_SRV_REPORT) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_SRV_REPORT.ProtoReflect.Descriptor instead.
func (*MSG_SRV_REPORT) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MSG_SRV_REPORT) GetSrvId() int64 {
	if x != nil {
		return x.SrvId
	}
	return 0
}

type MSG_TEST struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MSG_TEST) Reset() {
	*x = MSG_TEST{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_TEST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_TEST) ProtoMessage() {}

func (x *MSG_TEST) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_TEST.ProtoReflect.Descriptor instead.
func (*MSG_TEST) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MSG_TEST) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MSG_TEST_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MSG_TEST_RES) Reset() {
	*x = MSG_TEST_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_TEST_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_TEST_RES) ProtoMessage() {}

func (x *MSG_TEST_RES) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_TEST_RES.ProtoReflect.Descriptor instead.
func (*MSG_TEST_RES) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *MSG_TEST_RES) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MSG_LOGIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MSG_LOGIN) Reset() {
	*x = MSG_LOGIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_LOGIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_LOGIN) ProtoMessage() {}

func (x *MSG_LOGIN) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_LOGIN.ProtoReflect.Descriptor instead.
func (*MSG_LOGIN) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

func (x *MSG_LOGIN) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MSG_LOGIN_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConnectId int64 `protobuf:"varint,2,opt,name=connect_id,json=connectId,proto3" json:"connect_id,omitempty"`
}

func (x *MSG_LOGIN_RES) Reset() {
	*x = MSG_LOGIN_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_LOGIN_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_LOGIN_RES) ProtoMessage() {}

func (x *MSG_LOGIN_RES) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_LOGIN_RES.ProtoReflect.Descriptor instead.
func (*MSG_LOGIN_RES) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{6}
}

func (x *MSG_LOGIN_RES) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MSG_LOGIN_RES) GetConnectId() int64 {
	if x != nil {
		return x.ConnectId
	}
	return 0
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x73, 0x67,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x54, 0x0a, 0x07, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x50,
	0x43, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x73, 0x67, 0x42, 0x69, 0x6e, 0x22, 0x58, 0x0a, 0x0b,
	0x4d, 0x53, 0x47, 0x5f, 0x52, 0x50, 0x43, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6d, 0x73, 0x67, 0x42, 0x69, 0x6e, 0x22, 0x27, 0x0a, 0x0e, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x52,
	0x56, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x72, 0x76, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x72, 0x76, 0x49, 0x64, 0x22,
	0x1a, 0x0a, 0x08, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x4d,
	0x53, 0x47, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x09, 0x4d,
	0x53, 0x47, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x0d, 0x4d, 0x53, 0x47, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x64, 0x2a, 0xa2, 0x01, 0x0a, 0x08, 0x4d, 0x53, 0x47,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x4e, 0x55,
	0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x50, 0x43,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x50, 0x43, 0x5f, 0x52,
	0x45, 0x53, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x52, 0x56,
	0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x5f, 0x4d, 0x53,
	0x47, 0x5f, 0x4d, 0x41, 0x58, 0x10, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x4d, 0x53, 0x47, 0x5f,
	0x54, 0x45, 0x53, 0x54, 0x10, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x54,
	0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x66, 0x12, 0x0e, 0x0a, 0x0a, 0x5f, 0x4d, 0x53,
	0x47, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x67, 0x12, 0x12, 0x0a, 0x0e, 0x5f, 0x4d, 0x53,
	0x47, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x68, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2f, 0x3b, 0x6d, 0x73, 0x67, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_msg_proto_goTypes = []interface{}{
	(MSG_TYPE)(0),          // 0: msgpacket.MSG_TYPE
	(*MSG_RPC)(nil),        // 1: msgpacket.MSG_RPC
	(*MSG_RPC_RES)(nil),    // 2: msgpacket.MSG_RPC_RES
	(*MSG_SRV_REPORT)(nil), // 3: msgpacket.MSG_SRV_REPORT
	(*MSG_TEST)(nil),       // 4: msgpacket.MSG_TEST
	(*MSG_TEST_RES)(nil),   // 5: msgpacket.MSG_TEST_RES
	(*MSG_LOGIN)(nil),      // 6: msgpacket.MSG_LOGIN
	(*MSG_LOGIN_RES)(nil),  // 7: msgpacket.MSG_LOGIN_RES
}
var file_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_RPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_RPC_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_SRV_REPORT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_TEST); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_TEST_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_LOGIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_LOGIN_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
