// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.1
// source: msgDB.proto

package msgpacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBUserKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DBUserKey) Reset() {
	*x = DBUserKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgDB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBUserKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUserKey) ProtoMessage() {}

func (x *DBUserKey) ProtoReflect() protoreflect.Message {
	mi := &file_msgDB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUserKey.ProtoReflect.Descriptor instead.
func (*DBUserKey) Descriptor() ([]byte, []int) {
	return file_msgDB_proto_rawDescGZIP(), []int{0}
}

func (x *DBUserKey) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DBUserDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DetailData string `protobuf:"bytes,1,opt,name=detail_data,json=detailData,proto3" json:"detail_data,omitempty"`
	DetailId   int32  `protobuf:"varint,2,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"`
}

func (x *DBUserDetail) Reset() {
	*x = DBUserDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgDB_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBUserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUserDetail) ProtoMessage() {}

func (x *DBUserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_msgDB_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUserDetail.ProtoReflect.Descriptor instead.
func (*DBUserDetail) Descriptor() ([]byte, []int) {
	return file_msgDB_proto_rawDescGZIP(), []int{1}
}

func (x *DBUserDetail) GetDetailData() string {
	if x != nil {
		return x.DetailData
	}
	return ""
}

func (x *DBUserDetail) GetDetailId() int32 {
	if x != nil {
		return x.DetailId
	}
	return 0
}

type DBMapTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapStr string `protobuf:"bytes,1,opt,name=map_str,json=mapStr,proto3" json:"map_str,omitempty"`
	MapInt int64  `protobuf:"varint,2,opt,name=map_int,json=mapInt,proto3" json:"map_int,omitempty"`
}

func (x *DBMapTest) Reset() {
	*x = DBMapTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgDB_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBMapTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMapTest) ProtoMessage() {}

func (x *DBMapTest) ProtoReflect() protoreflect.Message {
	mi := &file_msgDB_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMapTest.ProtoReflect.Descriptor instead.
func (*DBMapTest) Descriptor() ([]byte, []int) {
	return file_msgDB_proto_rawDescGZIP(), []int{2}
}

func (x *DBMapTest) GetMapStr() string {
	if x != nil {
		return x.MapStr
	}
	return ""
}

func (x *DBMapTest) GetMapInt() int64 {
	if x != nil {
		return x.MapInt
	}
	return 0
}

type DBRepeatedTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepeatedStr string               `protobuf:"bytes,1,opt,name=repeated_str,json=repeatedStr,proto3" json:"repeated_str,omitempty"`
	RepeatedInt int64                `protobuf:"varint,2,opt,name=repeated_int,json=repeatedInt,proto3" json:"repeated_int,omitempty"`
	TestMap     map[int64]*DBMapTest `protobuf:"bytes,3,rep,name=test_map,json=testMap,proto3" json:"test_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DBRepeatedTest) Reset() {
	*x = DBRepeatedTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgDB_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBRepeatedTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRepeatedTest) ProtoMessage() {}

func (x *DBRepeatedTest) ProtoReflect() protoreflect.Message {
	mi := &file_msgDB_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRepeatedTest.ProtoReflect.Descriptor instead.
func (*DBRepeatedTest) Descriptor() ([]byte, []int) {
	return file_msgDB_proto_rawDescGZIP(), []int{3}
}

func (x *DBRepeatedTest) GetRepeatedStr() string {
	if x != nil {
		return x.RepeatedStr
	}
	return ""
}

func (x *DBRepeatedTest) GetRepeatedInt() int64 {
	if x != nil {
		return x.RepeatedInt
	}
	return 0
}

func (x *DBRepeatedTest) GetTestMap() map[int64]*DBMapTest {
	if x != nil {
		return x.TestMap
	}
	return nil
}

type DBUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XId          string            `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	UserId       int64             `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Detail       *DBUserDetail     `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	TestRepeated []*DBRepeatedTest `protobuf:"bytes,4,rep,name=test_repeated,json=testRepeated,proto3" json:"test_repeated,omitempty"`
}

func (x *DBUser) Reset() {
	*x = DBUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgDB_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUser) ProtoMessage() {}

func (x *DBUser) ProtoReflect() protoreflect.Message {
	mi := &file_msgDB_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUser.ProtoReflect.Descriptor instead.
func (*DBUser) Descriptor() ([]byte, []int) {
	return file_msgDB_proto_rawDescGZIP(), []int{4}
}

func (x *DBUser) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *DBUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DBUser) GetDetail() *DBUserDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *DBUser) GetTestRepeated() []*DBRepeatedTest {
	if x != nil {
		return x.TestRepeated
	}
	return nil
}

var File_msgDB_proto protoreflect.FileDescriptor

var file_msgDB_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x44, 0x42, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d,
	0x73, 0x67, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x24, 0x0a, 0x09, 0x44, 0x42, 0x55, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4c,
	0x0a, 0x0c, 0x44, 0x42, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x09,
	0x44, 0x42, 0x4d, 0x61, 0x70, 0x54, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x70,
	0x5f, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x70, 0x53,
	0x74, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x70, 0x49, 0x6e, 0x74, 0x22, 0xeb, 0x01, 0x0a, 0x0e,
	0x44, 0x42, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74,
	0x72, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x49, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x73, 0x67, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x44, 0x42, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x74, 0x65, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x1a, 0x50, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x42, 0x4d, 0x61, 0x70, 0x54, 0x65, 0x73, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa3, 0x01, 0x0a, 0x06, 0x44, 0x42,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x0f, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2f,
	0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6d, 0x73, 0x67, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x42, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x3e, 0x0a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x73, 0x67, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x44, 0x42, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x6d, 0x73, 0x67, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgDB_proto_rawDescOnce sync.Once
	file_msgDB_proto_rawDescData = file_msgDB_proto_rawDesc
)

func file_msgDB_proto_rawDescGZIP() []byte {
	file_msgDB_proto_rawDescOnce.Do(func() {
		file_msgDB_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgDB_proto_rawDescData)
	})
	return file_msgDB_proto_rawDescData
}

var file_msgDB_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msgDB_proto_goTypes = []interface{}{
	(*DBUserKey)(nil),      // 0: msgpacket.DBUserKey
	(*DBUserDetail)(nil),   // 1: msgpacket.DBUserDetail
	(*DBMapTest)(nil),      // 2: msgpacket.DBMapTest
	(*DBRepeatedTest)(nil), // 3: msgpacket.DBRepeatedTest
	(*DBUser)(nil),         // 4: msgpacket.DBUser
	nil,                    // 5: msgpacket.DBRepeatedTest.TestMapEntry
}
var file_msgDB_proto_depIdxs = []int32{
	5, // 0: msgpacket.DBRepeatedTest.test_map:type_name -> msgpacket.DBRepeatedTest.TestMapEntry
	1, // 1: msgpacket.DBUser.detail:type_name -> msgpacket.DBUserDetail
	3, // 2: msgpacket.DBUser.test_repeated:type_name -> msgpacket.DBRepeatedTest
	2, // 3: msgpacket.DBRepeatedTest.TestMapEntry.value:type_name -> msgpacket.DBMapTest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msgDB_proto_init() }
func file_msgDB_proto_init() {
	if File_msgDB_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgDB_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBUserKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgDB_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBUserDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgDB_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMapTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgDB_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBRepeatedTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgDB_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgDB_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgDB_proto_goTypes,
		DependencyIndexes: file_msgDB_proto_depIdxs,
		MessageInfos:      file_msgDB_proto_msgTypes,
	}.Build()
	File_msgDB_proto = out.File
	file_msgDB_proto_rawDesc = nil
	file_msgDB_proto_goTypes = nil
	file_msgDB_proto_depIdxs = nil
}
